FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY /consumer /consumer
COPY /rabbitapi /rabbitapi
RUN dotnet restore /rabbitapi/rabbitapi.csproj
RUN dotnet restore /consumer/consumer.csproj
RUN dotnet publish /consumer/consumer.csproj -c Release -o /app/out

FROM microsoft/dotnet:2.1-runtime-stretch-slim
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "consumer.dll"]